---
- name: Linux Health Check
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Get uptime
      command: uptime
      register: uptime_output

    - name: Check CPU load
      command: top -bn1 | grep "load average"
      register: cpu_load

    - name: Check memory usage
      command: free -m
      register: memory_usage

    - name: Check disk usage
      command: df -h
      register: disk_usage

    - name: Save report locally
      copy:
        content: |
          ===== Health Check Report =====

          Host: {{ inventory_hostname }}

          --- Uptime ---
          {{ uptime_output.stdout }}

          --- CPU Load ---
          {{ cpu_load.stdout }}

          --- Memory Usage ---
          {{ memory_usage.stdout }}

          --- Disk Usage ---
          {{ disk_usage.stdout }}

            dest: "./reports/{{ inventory_hostname }}_report.txt"
      delegate_to: vm01
