---
- name: Server Connectivity Check and Save Report
  hosts: all
  become: true
  gather_facts: yes

  tasks:

    - name: Ping test
      ansible.builtin.ping:
      register: ping_result

    - name: Get uptime
      command: uptime
      register: uptime_output

    - name: Create report content
      set_fact:
        report: |
          ===== Server Health Report =====

          Host: {{ inventory_hostname }}

          --- Ping ---
          {{ ping_result.ping }}

          --- Uptime ---
          {{ uptime_output.stdout }}

    - name: Save report to local file
      copy:
        content: "{{ report }}"
        dest: "./reports/{{ inventory_hostname }}.txt"
      delegate_to: vm01

    - name: Send email with report
      mail:
        host: smtp.gmail.com
        port: 587
        username: "asifali388@gmail.com"
        password: "Kpmst@123"
        to: "asifali388@gmail.com"
        subject: "Server Report - {{ inventory_hostname }}"
        body: "{{ report }}"
      delegate_to: vm01
